window.HERB_DATA = [
  {
    "id": 1,
    "hanja": "草豆蔲",
    "hangul": "초두구",
    "name": "草豆蔲(초두구)",
    "groupKey": "A",
    "groupTitle": "A그룹: 큰 향신료·둥근 과실 씨앗류",
    "source": "12주차까지",
    "photoPage": 2,
    "namePage": 3,
    "tip": "둥근 줄무늬 알들이 콩처럼 모였다 -> 草豆蔲, 초두구는 '풀밭 콩 두구'.",
    "image": "assets/001.jpeg"
  },
  {
    "id": 2,
    "hanja": "草果",
    "hangul": "초과",
    "name": "草果(초과)",
    "groupKey": "A",
    "groupTitle": "A그룹: 큰 향신료·둥근 과실 씨앗류",
    "source": "12주차까지",
    "photoPage": 4,
    "namePage": 5,
    "tip": "깨진 큰 꼬투리 조각이 거친 과실 껍데기처럼 흩어졌다 -> 草果.",
    "image": "assets/002.jpeg"
  },
  {
    "id": 3,
    "hanja": "佩蘭",
    "hangul": "패란",
    "name": "佩蘭(패란)",
    "groupKey": "F",
    "groupTitle": "F그룹: 잎·전초·줄기 조각류",
    "source": "12주차까지",
    "photoPage": 6,
    "namePage": 7,
    "tip": "잎줄기 조각이 패처럼 잘려 널렸다 -> 佩蘭은 '패 조각 난 잎'.",
    "image": "assets/003.jpeg"
  },
  {
    "id": 4,
    "hanja": "茯苓",
    "hangul": "복령",
    "name": "茯苓(복령)",
    "groupKey": "C",
    "groupTitle": "C그룹: 흰색·담색 절편과 원형 절편류",
    "source": "12주차까지",
    "photoPage": 8,
    "namePage": 9,
    "tip": "하얀 부스러기 구름덩이처럼 보이면 복슬복슬 茯苓.",
    "image": "assets/004.jpeg"
  },
  {
    "id": 5,
    "hanja": "猪苓",
    "hangul": "저령",
    "name": "猪苓(저령)",
    "groupKey": "C",
    "groupTitle": "C그룹: 흰색·담색 절편과 원형 절편류",
    "source": "12주차까지",
    "photoPage": 10,
    "namePage": 11,
    "tip": "검은 껍질 붙은 흰 조각이 돼지 얼룩처럼 보인다 -> 猪苓.",
    "image": "assets/005.jpeg"
  },
  {
    "id": 6,
    "hanja": "澤瀉",
    "hangul": "택사",
    "name": "澤瀉(택사)",
    "groupKey": "C",
    "groupTitle": "C그룹: 흰색·담색 절편과 원형 절편류",
    "source": "12주차까지",
    "photoPage": 12,
    "namePage": 13,
    "tip": "둥근 흰 절편에 물가의 둑 같은 테가 보인다 -> 澤瀉.",
    "image": "assets/006.jpeg"
  },
  {
    "id": 7,
    "hanja": "意苡仁",
    "hangul": "의이인",
    "name": "意苡仁(의이인)",
    "groupKey": "B",
    "groupTitle": "B그룹: 작은 씨앗·곡물 알갱이류",
    "source": "12주차까지",
    "photoPage": 14,
    "namePage": 15,
    "tip": "하얀 구슬 곡식이 의자 위에 좌르륵 -> 意苡仁, '의이인 알'.",
    "image": "assets/007.jpeg"
  },
  {
    "id": 8,
    "hanja": "冬瓜皮",
    "hangul": "동과피",
    "name": "冬瓜皮(동과피)",
    "groupKey": "G",
    "groupTitle": "G그룹: 껍질·판상 조각류",
    "source": "12주차까지",
    "photoPage": 16,
    "namePage": 17,
    "tip": "초록 껍질 조각이 겨울참외 껍데기처럼 납작하다 -> 冬瓜皮.",
    "image": "assets/008.jpeg"
  },
  {
    "id": 9,
    "hanja": "赤小豆",
    "hangul": "적소두",
    "name": "赤小豆(적소두)",
    "groupKey": "B",
    "groupTitle": "B그룹: 작은 씨앗·곡물 알갱이류",
    "source": "12주차까지",
    "photoPage": 18,
    "namePage": 19,
    "tip": "붉은 작은 콩이 그대로 보이면 이름도 직설적이다 -> 赤小豆.",
    "image": "assets/009.jpeg"
  },
  {
    "id": 10,
    "hanja": "玉蜀黍蕊",
    "hangul": "옥촉서예",
    "name": "玉蜀黍蕊(옥촉서예)",
    "groupKey": "easy",
    "groupTitle": "바로 알아보기 쉬운 약재",
    "source": "12주차까지",
    "photoPage": 20,
    "namePage": 21,
    "tip": "헝클어진 옥수수 수염 한 움큼 -> 玉蜀黍蕊, 옥촉서예.",
    "image": "assets/010.jpeg"
  },
  {
    "id": 11,
    "hanja": "車前子",
    "hangul": "차전자",
    "name": "車前子(차전자)",
    "groupKey": "B",
    "groupTitle": "B그룹: 작은 씨앗·곡물 알갱이류",
    "source": "12주차까지",
    "photoPage": 22,
    "namePage": 23,
    "tip": "까만 모래알이 차바퀴 자국처럼 빽빽하다 -> 車前子.",
    "image": "assets/011.jpeg"
  },
  {
    "id": 12,
    "hanja": "木通",
    "hangul": "목통",
    "name": "木通(목통)",
    "groupKey": "C",
    "groupTitle": "C그룹: 흰색·담색 절편과 원형 절편류",
    "source": "12주차까지",
    "photoPage": 24,
    "namePage": 25,
    "tip": "구멍 뚫린 흰 줄기 절편이 나무 파이프처럼 보인다 -> 木通.",
    "image": "assets/012.jpeg"
  },
  {
    "id": 13,
    "hanja": "滑石",
    "hangul": "활석",
    "name": "滑石(활석)",
    "groupKey": "L",
    "groupTitle": "L그룹: 광물·분말·돌가루류",
    "source": "12주차까지",
    "photoPage": 26,
    "namePage": 27,
    "tip": "그릇 속 새하얀 돌가루 -> 滑石, 미끄러운 흰 석분.",
    "image": "assets/013.jpeg"
  },
  {
    "id": 14,
    "hanja": "通草",
    "hangul": "통초",
    "name": "通草(통초)",
    "groupKey": "C",
    "groupTitle": "C그룹: 흰색·담색 절편과 원형 절편류",
    "source": "12주차까지",
    "photoPage": 28,
    "namePage": 29,
    "tip": "가운데 심이 하얀 동그라미 절편 -> 通草는 속이 통하는 통초.",
    "image": "assets/014.jpeg"
  },
  {
    "id": 15,
    "hanja": "海金沙",
    "hangul": "해금사",
    "name": "海金沙(해금사)",
    "groupKey": "L",
    "groupTitle": "L그룹: 광물·분말·돌가루류",
    "source": "12주차까지",
    "photoPage": 30,
    "namePage": 31,
    "tip": "금빛 갈색 가루가 모래처럼 고르게 깔렸다 -> 海金沙, 금빛 沙.",
    "image": "assets/015.jpeg"
  },
  {
    "id": 16,
    "hanja": "石韋",
    "hangul": "석위",
    "name": "石韋(석위)",
    "groupKey": "F",
    "groupTitle": "F그룹: 잎·전초·줄기 조각류",
    "source": "12주차까지",
    "photoPage": 32,
    "namePage": 33,
    "tip": "마른 잎 조각이 돌 틈에 붙은 잎처럼 보인다 -> 石韋, 葦가 아니라 韋.",
    "image": "assets/016.jpeg"
  },
  {
    "id": 17,
    "hanja": "萆薢",
    "hangul": "비해",
    "name": "萆薢(비해)",
    "groupKey": "C",
    "groupTitle": "C그룹: 흰색·담색 절편과 원형 절편류",
    "source": "12주차까지",
    "photoPage": 34,
    "namePage": 35,
    "tip": "얇고 흰 껍질 조각이 비스듬히 벗겨졌다 -> 萆薢는 '비껴 벗겨진 비해'.",
    "image": "assets/017.jpeg"
  },
  {
    "id": 18,
    "hanja": "地膚子",
    "hangul": "지부자",
    "name": "地膚子(지부자)",
    "groupKey": "B",
    "groupTitle": "B그룹: 작은 씨앗·곡물 알갱이류",
    "source": "12주차까지",
    "photoPage": 36,
    "namePage": 37,
    "tip": "작은 갈색 알들이 땅바닥에 촘촘하다 -> 地膚子.",
    "image": "assets/018.jpeg"
  },
  {
    "id": 19,
    "hanja": "萹蓄",
    "hangul": "편축",
    "name": "萹蓄(편축)",
    "groupKey": "F",
    "groupTitle": "F그룹: 잎·전초·줄기 조각류",
    "source": "12주차까지",
    "photoPage": 38,
    "namePage": 39,
    "tip": "가느다란 줄기와 잎이 납작하게 편 조각 -> 萹蓄.",
    "image": "assets/019.jpeg"
  },
  {
    "id": 20,
    "hanja": "瞿麥",
    "hangul": "구맥",
    "name": "瞿麥(구맥)",
    "groupKey": "F",
    "groupTitle": "F그룹: 잎·전초·줄기 조각류",
    "source": "12주차까지",
    "photoPage": 40,
    "namePage": 41,
    "tip": "마른 줄기 조각이 창끝처럼 삐죽삐죽 -> 瞿麥.",
    "image": "assets/020.jpeg"
  },
  {
    "id": 21,
    "hanja": "冬葵子",
    "hangul": "동규자",
    "name": "冬葵子(동규자)",
    "groupKey": "B",
    "groupTitle": "B그룹: 작은 씨앗·곡물 알갱이류",
    "source": "12주차까지",
    "photoPage": 42,
    "namePage": 43,
    "tip": "납작한 동그란 씨앗이 동글동글 모였다 -> 冬葵子.",
    "image": "assets/021.jpeg"
  },
  {
    "id": 22,
    "hanja": "燈心草",
    "hangul": "등심초",
    "name": "燈心草(등심초)",
    "groupKey": "easy",
    "groupTitle": "바로 알아보기 쉬운 약재",
    "source": "12주차까지",
    "photoPage": 44,
    "namePage": 45,
    "tip": "하얀 실오라기가 등잔 심지처럼 길게 뻗었다 -> 燈心草.",
    "image": "assets/022.jpeg"
  },
  {
    "id": 23,
    "hanja": "三白草",
    "hangul": "삼백초",
    "name": "三白草(삼백초)",
    "groupKey": "F",
    "groupTitle": "F그룹: 잎·전초·줄기 조각류",
    "source": "12주차까지",
    "photoPage": 46,
    "namePage": 47,
    "tip": "초록 잎 조각 사이 흰 줄기가 섞였다 -> 三白草, 흰 기운 세 번.",
    "image": "assets/023.jpeg"
  },
  {
    "id": 24,
    "hanja": "茵蔯蒿",
    "hangul": "인진호",
    "name": "茵蔯蒿(인진호)",
    "groupKey": "F",
    "groupTitle": "F그룹: 잎·전초·줄기 조각류",
    "source": "12주차까지",
    "photoPage": 48,
    "namePage": 49,
    "tip": "잿빛 솜뭉치처럼 흐린 풀더미 -> 茵蔯蒿.",
    "image": "assets/024.jpeg"
  },
  {
    "id": 25,
    "hanja": "金錢草",
    "hangul": "금전초",
    "name": "金錢草(금전초)",
    "groupKey": "F",
    "groupTitle": "F그룹: 잎·전초·줄기 조각류",
    "source": "12주차까지",
    "photoPage": 50,
    "namePage": 51,
    "tip": "동전 같은 잎 조각이 어둡게 말라 있다 -> 金錢草.",
    "image": "assets/025.jpeg"
  },
  {
    "id": 26,
    "hanja": "附子",
    "hangul": "부자",
    "name": "附子(부자)",
    "groupKey": "K",
    "groupTitle": "K그룹: 수지·검은 덩어리류",
    "source": "12주차까지",
    "photoPage": 52,
    "namePage": 53,
    "tip": "검은 덩이가 붙어서 무섭게 눌린 모양 -> 附子.",
    "image": "assets/026.jpeg"
  },
  {
    "id": 27,
    "hanja": "川烏頭",
    "hangul": "천오두",
    "name": "川烏頭(천오두)",
    "groupKey": "D",
    "groupTitle": "D그룹: 갈색 뿌리·근경 절편류",
    "source": "12주차까지",
    "photoPage": 54,
    "namePage": 55,
    "tip": "검은 껍질과 흰 속살이 뒤섞인 덩어리 -> 川烏頭.",
    "image": "assets/027.jpeg"
  },
  {
    "id": 28,
    "hanja": "乾薑",
    "hangul": "건강",
    "name": "乾薑(건강)",
    "groupKey": "C",
    "groupTitle": "C그룹: 흰색·담색 절편과 원형 절편류",
    "source": "12주차까지",
    "photoPage": 56,
    "namePage": 57,
    "tip": "말린 생강 조각처럼 노랗고 섬유가 보이면 -> 乾薑.",
    "image": "assets/028.jpeg"
  },
  {
    "id": 29,
    "hanja": "肉桂",
    "hangul": "육계",
    "name": "肉桂(육계)",
    "groupKey": "G",
    "groupTitle": "G그룹: 껍질·판상 조각류",
    "source": "12주차까지",
    "photoPage": 58,
    "namePage": 59,
    "tip": "갈색 네모 껍질이 계피 판처럼 잘렸다 -> 肉桂.",
    "image": "assets/029.jpeg"
  },
  {
    "id": 30,
    "hanja": "吳茱萸",
    "hangul": "오수유",
    "name": "吳茱萸(오수유)",
    "groupKey": "A",
    "groupTitle": "A그룹: 큰 향신료·둥근 과실 씨앗류",
    "source": "12주차까지",
    "photoPage": 60,
    "namePage": 61,
    "tip": "오돌토돌한 갈색 열매가 오수수 모였다 -> 吳茱萸.",
    "image": "assets/030.jpeg"
  },
  {
    "id": 31,
    "hanja": "蜀椒",
    "hangul": "촉초",
    "name": "蜀椒(촉초)",
    "groupKey": "A",
    "groupTitle": "A그룹: 큰 향신료·둥근 과실 씨앗류",
    "source": "12주차까지",
    "photoPage": 62,
    "namePage": 63,
    "tip": "붉은 작은 껍질 알이 톡톡 튄다 -> 蜀椒, 촉의 산초.",
    "image": "assets/031.jpeg"
  },
  {
    "id": 32,
    "hanja": "蓽撥",
    "hangul": "필발",
    "name": "蓽撥(필발)",
    "groupKey": "H",
    "groupTitle": "H그룹: 목재 막대·긴 향신료류",
    "source": "12주차까지",
    "photoPage": 64,
    "namePage": 65,
    "tip": "검은 짧은 막대 향신료가 삐뚤빼뚤 -> 蓽撥.",
    "image": "assets/032.jpeg"
  },
  {
    "id": 33,
    "hanja": "蓽澄茄",
    "hangul": "필징가",
    "name": "蓽澄茄(필징가)",
    "groupKey": "A",
    "groupTitle": "A그룹: 큰 향신료·둥근 과실 씨앗류",
    "source": "12주차까지",
    "photoPage": 66,
    "namePage": 67,
    "tip": "검은 동그란 알이 필름처럼 빽빽하다 -> 蓽澄茄.",
    "image": "assets/033.jpeg"
  },
  {
    "id": 34,
    "hanja": "丁香",
    "hangul": "정향",
    "name": "丁香(정향)",
    "groupKey": "I",
    "groupTitle": "I그룹: 꽃·꽃봉오리류",
    "source": "12주차까지",
    "photoPage": 68,
    "namePage": 69,
    "tip": "못처럼 생긴 꽃봉오리 하나하나 -> 丁香, '정향 못'.",
    "image": "assets/034.jpeg"
  },
  {
    "id": 35,
    "hanja": "高良薑",
    "hangul": "고량강",
    "name": "高良薑(고량강)",
    "groupKey": "D",
    "groupTitle": "D그룹: 갈색 뿌리·근경 절편류",
    "source": "12주차까지",
    "photoPage": 70,
    "namePage": 71,
    "tip": "생강보다 더 각진 갈색 절편 -> 高良薑.",
    "image": "assets/035.jpeg"
  },
  {
    "id": 36,
    "hanja": "小茴香",
    "hangul": "소회향",
    "name": "小茴香(소회향)",
    "groupKey": "B",
    "groupTitle": "B그룹: 작은 씨앗·곡물 알갱이류",
    "source": "12주차까지",
    "photoPage": 72,
    "namePage": 73,
    "tip": "초록 줄무늬 타원 씨앗이 작은 회향 냄새를 부른다 -> 小茴香.",
    "image": "assets/036.jpeg"
  },
  {
    "id": 37,
    "hanja": "胡椒",
    "hangul": "호초",
    "name": "胡椒(호초)",
    "groupKey": "A",
    "groupTitle": "A그룹: 큰 향신료·둥근 과실 씨앗류",
    "source": "12주차까지",
    "photoPage": 74,
    "namePage": 75,
    "tip": "후추알 그대로 검은 점들이 흩어졌다 -> 胡椒.",
    "image": "assets/037.jpeg"
  },
  {
    "id": 38,
    "hanja": "陳皮",
    "hangul": "진피",
    "name": "陳皮(진피)",
    "groupKey": "G",
    "groupTitle": "G그룹: 껍질·판상 조각류",
    "source": "12주차까지",
    "photoPage": 76,
    "namePage": 77,
    "tip": "주황 껍질 조각이면 오래 묵은 귤껍질 -> 陳皮.",
    "image": "assets/038.jpeg"
  },
  {
    "id": 39,
    "hanja": "靑皮",
    "hangul": "청피",
    "name": "靑皮(청피)",
    "groupKey": "G",
    "groupTitle": "G그룹: 껍질·판상 조각류",
    "source": "12주차까지",
    "photoPage": 78,
    "namePage": 79,
    "tip": "초록 껍질이 흰 안쪽을 드러낸다 -> 靑皮.",
    "image": "assets/039.jpeg"
  },
  {
    "id": 40,
    "hanja": "枳實",
    "hangul": "지실",
    "name": "枳實(지실)",
    "groupKey": "A",
    "groupTitle": "A그룹: 큰 향신료·둥근 과실 씨앗류",
    "source": "12주차까지",
    "photoPage": 80,
    "namePage": 81,
    "tip": "둥근 과실 절편 속 점무늬가 보인다 -> 枳實.",
    "image": "assets/040.jpeg"
  },
  {
    "id": 41,
    "hanja": "枳殼",
    "hangul": "지각",
    "name": "枳殼(지각)",
    "groupKey": "A",
    "groupTitle": "A그룹: 큰 향신료·둥근 과실 씨앗류",
    "source": "12주차까지",
    "photoPage": 82,
    "namePage": 83,
    "tip": "큰 귤껍질 배 조각처럼 휘어진다 -> 枳殼.",
    "image": "assets/041.jpeg"
  },
  {
    "id": 42,
    "hanja": "木香",
    "hangul": "목향",
    "name": "木香(목향)",
    "groupKey": "D",
    "groupTitle": "D그룹: 갈색 뿌리·근경 절편류",
    "source": "12주차까지",
    "photoPage": 84,
    "namePage": 85,
    "tip": "둥근 갈색 뿌리 절편이 목각 단면처럼 보인다 -> 木香.",
    "image": "assets/042.jpeg"
  },
  {
    "id": 43,
    "hanja": "香附子",
    "hangul": "향부자",
    "name": "香附子(향부자)",
    "groupKey": "D",
    "groupTitle": "D그룹: 갈색 뿌리·근경 절편류",
    "source": "12주차까지",
    "photoPage": 86,
    "namePage": 87,
    "tip": "작은 갈색 덩이가 향 주머니처럼 모였다 -> 香附子.",
    "image": "assets/043.jpeg"
  },
  {
    "id": 44,
    "hanja": "烏藥",
    "hangul": "오약",
    "name": "烏藥(오약)",
    "groupKey": "D",
    "groupTitle": "D그룹: 갈색 뿌리·근경 절편류",
    "source": "12주차까지",
    "photoPage": 88,
    "namePage": 89,
    "tip": "동글 납작한 흰 절편에 검은 테가 둘렸다 -> 烏藥.",
    "image": "assets/044.jpeg"
  },
  {
    "id": 45,
    "hanja": "沈香",
    "hangul": "침향",
    "name": "沈香(침향)",
    "groupKey": "G",
    "groupTitle": "G그룹: 껍질·판상 조각류",
    "source": "12주차까지",
    "photoPage": 90,
    "namePage": 91,
    "tip": "검고 묵직한 향목 한 조각이 물에 잠긴 듯하다 -> 沈香.",
    "image": "assets/045.jpeg"
  },
  {
    "id": 46,
    "hanja": "川楝子",
    "hangul": "천련자",
    "name": "川楝子(천련자)",
    "groupKey": "D",
    "groupTitle": "D그룹: 갈색 뿌리·근경 절편류",
    "source": "12주차까지",
    "photoPage": 92,
    "namePage": 93,
    "tip": "동그란 갈색 절편에 가운데 눈이 보인다 -> 川楝子.",
    "image": "assets/046.jpeg"
  },
  {
    "id": 47,
    "hanja": "荔枝核",
    "hangul": "여지핵",
    "name": "荔枝核(여지핵)",
    "groupKey": "A",
    "groupTitle": "A그룹: 큰 향신료·둥근 과실 씨앗류",
    "source": "12주차까지",
    "photoPage": 94,
    "namePage": 95,
    "tip": "반질반질한 밤색 씨가 리치 핵처럼 단단하다 -> 荔枝核.",
    "image": "assets/047.jpeg"
  },
  {
    "id": 48,
    "hanja": "靑木香",
    "hangul": "청목향",
    "name": "靑木香(청목향)",
    "groupKey": "D",
    "groupTitle": "D그룹: 갈색 뿌리·근경 절편류",
    "source": "12주차까지",
    "photoPage": 96,
    "namePage": 97,
    "tip": "길쭉한 회갈색 뿌리가 푸른 이름을 숨긴다 -> 靑木香.",
    "image": "assets/048.jpeg"
  },
  {
    "id": 49,
    "hanja": "薤白",
    "hangul": "해백",
    "name": "薤白(해백)",
    "groupKey": "J",
    "groupTitle": "J그룹: 막질·껍데기 조각류",
    "source": "12주차까지",
    "photoPage": 98,
    "namePage": 99,
    "tip": "투명한 비늘 조각이 마늘 껍질처럼 바삭하다 -> 薤白.",
    "image": "assets/049.jpeg"
  },
  {
    "id": 50,
    "hanja": "檀香",
    "hangul": "단향",
    "name": "檀香(단향)",
    "groupKey": "H",
    "groupTitle": "H그룹: 목재 막대·긴 향신료류",
    "source": "12주차까지",
    "photoPage": 100,
    "namePage": 101,
    "tip": "곧은 나무막대가 단정하게 놓였다 -> 檀香, 향목 단향.",
    "image": "assets/050.jpeg"
  },
  {
    "id": 51,
    "hanja": "柿蒂",
    "hangul": "시체",
    "name": "柿蒂(시체)",
    "groupKey": "easy",
    "groupTitle": "바로 알아보기 쉬운 약재",
    "source": "12주차까지",
    "photoPage": 102,
    "namePage": 103,
    "tip": "감 꼭지가 별처럼 딱 붙은 모양 -> 柿蒂, 감 꼭지 시체.",
    "image": "assets/051.jpeg"
  },
  {
    "id": 52,
    "hanja": "玫瑰花",
    "hangul": "매괴화",
    "name": "玫瑰花(매괴화)",
    "groupKey": "I",
    "groupTitle": "I그룹: 꽃·꽃봉오리류",
    "source": "12주차까지",
    "photoPage": 104,
    "namePage": 105,
    "tip": "작은 장미 봉오리가 그대로 말랐다 -> 玫瑰花.",
    "image": "assets/052.jpeg"
  },
  {
    "id": 53,
    "hanja": "大腹皮",
    "hangul": "대복피",
    "name": "大腹皮(대복피)",
    "groupKey": "J",
    "groupTitle": "J그룹: 막질·껍데기 조각류",
    "source": "12주차까지",
    "photoPage": 106,
    "namePage": 107,
    "tip": "넓은 껍질 조각이 배를 크게 벌린다 -> 大腹皮.",
    "image": "assets/053.jpeg"
  },
  {
    "id": 54,
    "hanja": "土木香",
    "hangul": "토목향",
    "name": "土木香(토목향)",
    "groupKey": "D",
    "groupTitle": "D그룹: 갈색 뿌리·근경 절편류",
    "source": "12주차까지",
    "photoPage": 108,
    "namePage": 109,
    "tip": "납작한 갈색 절편이 흙 묻은 목향처럼 보인다 -> 土木香.",
    "image": "assets/054.jpeg"
  },
  {
    "id": 55,
    "hanja": "甘松香",
    "hangul": "감송향",
    "name": "甘松香(감송향)",
    "groupKey": "D",
    "groupTitle": "D그룹: 갈색 뿌리·근경 절편류",
    "source": "12주차까지",
    "photoPage": 110,
    "namePage": 111,
    "tip": "검은 뿌리 실타래가 달콤한 향을 숨긴다 -> 甘松香.",
    "image": "assets/055.jpeg"
  },
  {
    "id": 56,
    "hanja": "山楂",
    "hangul": "산사",
    "name": "山楂(산사)",
    "groupKey": "D",
    "groupTitle": "D그룹: 갈색 뿌리·근경 절편류",
    "source": "12주차까지",
    "photoPage": 112,
    "namePage": 113,
    "tip": "빨간 테가 남은 산사 열매 동그라미 -> 山楂.",
    "image": "assets/056.jpeg"
  },
  {
    "id": 57,
    "hanja": "神麯",
    "hangul": "신곡",
    "name": "神麯(신곡)",
    "groupKey": "easy",
    "groupTitle": "바로 알아보기 쉬운 약재",
    "source": "12주차까지",
    "photoPage": 114,
    "namePage": 115,
    "tip": "회색 누룩 벽돌 조각처럼 네모나다 -> 神麯.",
    "image": "assets/057.jpeg"
  },
  {
    "id": 58,
    "hanja": "麥芽",
    "hangul": "맥아",
    "name": "麥芽(맥아)",
    "groupKey": "B",
    "groupTitle": "B그룹: 작은 씨앗·곡물 알갱이류",
    "source": "12주차까지",
    "photoPage": 116,
    "namePage": 117,
    "tip": "보리 싹이 튼 낱알이 한 방향으로 누웠다 -> 麥芽.",
    "image": "assets/058.jpeg"
  },
  {
    "id": 59,
    "hanja": "穀芽",
    "hangul": "곡아",
    "name": "穀芽(곡아)",
    "groupKey": "B",
    "groupTitle": "B그룹: 작은 씨앗·곡물 알갱이류",
    "source": "12주차까지",
    "photoPage": 118,
    "namePage": 119,
    "tip": "맥아보다 더 누런 곡식 싹 더미 -> 穀芽.",
    "image": "assets/059.jpeg"
  },
  {
    "id": 60,
    "hanja": "萊菔子",
    "hangul": "내복자",
    "name": "萊菔子(내복자)",
    "groupKey": "B",
    "groupTitle": "B그룹: 작은 씨앗·곡물 알갱이류",
    "source": "12주차까지",
    "photoPage": 120,
    "namePage": 121,
    "tip": "작은 갈색 무씨가 복작복작 모였다 -> 萊菔子.",
    "image": "assets/060.jpeg"
  },
  {
    "id": 61,
    "hanja": "鷄內金",
    "hangul": "계내금",
    "name": "鷄內金(계내금)",
    "groupKey": "J",
    "groupTitle": "J그룹: 막질·껍데기 조각류",
    "source": "12주차까지",
    "photoPage": 122,
    "namePage": 123,
    "tip": "얇은 노란 막 조각이 닭 모래주머니 안쪽처럼 보인다 -> 鷄內金.",
    "image": "assets/061.jpeg"
  },
  {
    "id": 62,
    "hanja": "使君子",
    "hangul": "사군자",
    "name": "使君子(사군자)",
    "groupKey": "A",
    "groupTitle": "A그룹: 큰 향신료·둥근 과실 씨앗류",
    "source": "12주차까지",
    "photoPage": 124,
    "namePage": 125,
    "tip": "초록 날개 달린 씨앗이 사군자 꽃배처럼 벌어졌다 -> 使君子.",
    "image": "assets/062.jpeg"
  },
  {
    "id": 63,
    "hanja": "苦楝皮",
    "hangul": "고련피",
    "name": "苦楝皮(고련피)",
    "groupKey": "G",
    "groupTitle": "G그룹: 껍질·판상 조각류",
    "source": "12주차까지",
    "photoPage": 126,
    "namePage": 127,
    "tip": "검고 노란 껍질 토막이 고련나무 껍질답다 -> 苦楝皮.",
    "image": "assets/063.jpeg"
  },
  {
    "id": 64,
    "hanja": "檳榔子",
    "hangul": "빈랑자",
    "name": "檳榔子(빈랑자)",
    "groupKey": "A",
    "groupTitle": "A그룹: 큰 향신료·둥근 과실 씨앗류",
    "source": "12주차까지",
    "photoPage": 128,
    "namePage": 129,
    "tip": "동전 같은 납작한 무늬 씨앗 -> 檳榔子.",
    "image": "assets/064.jpeg"
  },
  {
    "id": 65,
    "hanja": "雷丸",
    "hangul": "뇌환",
    "name": "雷丸(뇌환)",
    "groupKey": "D",
    "groupTitle": "D그룹: 갈색 뿌리·근경 절편류",
    "source": "12주차까지",
    "photoPage": 130,
    "namePage": 131,
    "tip": "검은 감자알 같은 둥근 덩어리 -> 雷丸.",
    "image": "assets/065.jpeg"
  },
  {
    "id": 66,
    "hanja": "鶴虱",
    "hangul": "학슬",
    "name": "鶴虱(학슬)",
    "groupKey": "B",
    "groupTitle": "B그룹: 작은 씨앗·곡물 알갱이류",
    "source": "12주차까지",
    "photoPage": 132,
    "namePage": 133,
    "tip": "컵 속 잔털 씨앗이 학의 깃털처럼 빽빽하다 -> 鶴虱.",
    "image": "assets/066.jpeg"
  },
  {
    "id": 67,
    "hanja": "榧子",
    "hangul": "비자",
    "name": "榧子(비자)",
    "groupKey": "A",
    "groupTitle": "A그룹: 큰 향신료·둥근 과실 씨앗류",
    "source": "12주차까지",
    "photoPage": 134,
    "namePage": 135,
    "tip": "큰 올리브색 씨앗이 비스듬히 누웠다 -> 榧子.",
    "image": "assets/067.jpeg"
  },
  {
    "id": 68,
    "hanja": "蕪荑",
    "hangul": "무이",
    "name": "蕪荑(무이)",
    "groupKey": "K",
    "groupTitle": "K그룹: 수지·검은 덩어리류",
    "source": "12주차까지",
    "photoPage": 136,
    "namePage": 137,
    "tip": "누런 덩어리가 무너진 흙덩이 같다 -> 蕪荑.",
    "image": "assets/068.jpeg"
  },
  {
    "id": 69,
    "hanja": "貫衆",
    "hangul": "관중",
    "name": "貫衆(관중)",
    "groupKey": "F",
    "groupTitle": "F그룹: 잎·전초·줄기 조각류",
    "source": "12주차까지",
    "photoPage": 138,
    "namePage": 139,
    "tip": "검은 섬유 덩어리가 관처럼 말렸다 -> 貫衆.",
    "image": "assets/069.jpeg"
  },
  {
    "id": 70,
    "hanja": "龍牙草",
    "hangul": "용아초",
    "name": "龍牙草(용아초)",
    "groupKey": "F",
    "groupTitle": "F그룹: 잎·전초·줄기 조각류",
    "source": "12주차까지",
    "photoPage": 140,
    "namePage": 141,
    "tip": "잘린 잎줄기가 용의 이빨 줄처럼 삐죽하다 -> 龍牙草.",
    "image": "assets/070.jpeg"
  },
  {
    "id": 71,
    "hanja": "白芨",
    "hangul": "백급",
    "name": "白芨(백급)",
    "groupKey": "C",
    "groupTitle": "C그룹: 흰색·담색 절편과 원형 절편류",
    "source": "12주차까지",
    "photoPage": 142,
    "namePage": 143,
    "tip": "하얀 구근 조각이 백색 조개처럼 벌어졌다 -> 白芨.",
    "image": "assets/071.jpeg"
  },
  {
    "id": 72,
    "hanja": "棕櫚皮",
    "hangul": "종려피",
    "name": "棕櫚皮(종려피)",
    "groupKey": "G",
    "groupTitle": "G그룹: 껍질·판상 조각류",
    "source": "12주차까지",
    "photoPage": 144,
    "namePage": 145,
    "tip": "갈색 판 조각이 야자 껍질처럼 층진다 -> 棕櫚皮.",
    "image": "assets/072.jpeg"
  },
  {
    "id": 73,
    "hanja": "藕節",
    "hangul": "우절",
    "name": "藕節(우절)",
    "groupKey": "easy",
    "groupTitle": "바로 알아보기 쉬운 약재",
    "source": "12주차까지",
    "photoPage": 146,
    "namePage": 147,
    "tip": "연근 마디 단면이 구멍까지 그대로 보인다 -> 藕節.",
    "image": "assets/073.jpeg"
  },
  {
    "id": 74,
    "hanja": "大薊",
    "hangul": "대계",
    "name": "大薊(대계)",
    "groupKey": "F",
    "groupTitle": "F그룹: 잎·전초·줄기 조각류",
    "source": "12주차까지",
    "photoPage": 148,
    "namePage": 149,
    "tip": "가시 섞인 줄기 조각이 큰 엉겅퀴답다 -> 大薊.",
    "image": "assets/074.jpeg"
  },
  {
    "id": 75,
    "hanja": "小薊",
    "hangul": "소계",
    "name": "小薊(소계)",
    "groupKey": "F",
    "groupTitle": "F그룹: 잎·전초·줄기 조각류",
    "source": "12주차까지",
    "photoPage": 150,
    "namePage": 151,
    "tip": "솜털 날린 작은 엉겅퀴 더미 -> 小薊.",
    "image": "assets/075.jpeg"
  },
  {
    "id": 76,
    "hanja": "地楡",
    "hangul": "지유",
    "name": "地楡(지유)",
    "groupKey": "D",
    "groupTitle": "D그룹: 갈색 뿌리·근경 절편류",
    "source": "12주차까지",
    "photoPage": 152,
    "namePage": 153,
    "tip": "갈색 뿌리 단면에 짙은 심이 보인다 -> 地楡.",
    "image": "assets/076.jpeg"
  },
  {
    "id": 77,
    "hanja": "槐花",
    "hangul": "괴화",
    "name": "槐花(괴화)",
    "groupKey": "B",
    "groupTitle": "B그룹: 작은 씨앗·곡물 알갱이류",
    "source": "12주차까지",
    "photoPage": 154,
    "namePage": 155,
    "tip": "작은 꽃봉오리 알이 회록색으로 모였다 -> 槐花.",
    "image": "assets/077.jpeg"
  },
  {
    "id": 78,
    "hanja": "側柏葉",
    "hangul": "측백엽",
    "name": "側柏葉(측백엽)",
    "groupKey": "F",
    "groupTitle": "F그룹: 잎·전초·줄기 조각류",
    "source": "12주차까지",
    "photoPage": 156,
    "namePage": 157,
    "tip": "측백 잎이 납작한 부채 조각처럼 보인다 -> 側柏葉.",
    "image": "assets/078.jpeg"
  },
  {
    "id": 79,
    "hanja": "白茅根",
    "hangul": "백모근",
    "name": "白茅根(백모근)",
    "groupKey": "C",
    "groupTitle": "C그룹: 흰색·담색 절편과 원형 절편류",
    "source": "12주차까지",
    "photoPage": 158,
    "namePage": 159,
    "tip": "하얀 짧은 뿌리 막대가 모근처럼 늘어섰다 -> 白茅根.",
    "image": "assets/079.jpeg"
  },
  {
    "id": 80,
    "hanja": "羊蹄根",
    "hangul": "양제근",
    "name": "羊蹄根(양제근)",
    "groupKey": "D",
    "groupTitle": "D그룹: 갈색 뿌리·근경 절편류",
    "source": "12주차까지",
    "photoPage": 160,
    "namePage": 161,
    "tip": "두꺼운 갈색 뿌리 절편이 양발굽처럼 투박하다 -> 羊蹄根.",
    "image": "assets/080.jpeg"
  },
  {
    "id": 81,
    "hanja": "三七",
    "hangul": "삼칠",
    "name": "三七(삼칠)",
    "groupKey": "easy",
    "groupTitle": "바로 알아보기 쉬운 약재",
    "source": "12주차까지",
    "photoPage": 162,
    "namePage": 163,
    "tip": "통통한 사람 모양 뿌리 덩이 -> 三七.",
    "image": "assets/081.jpeg"
  },
  {
    "id": 82,
    "hanja": "蒲黃",
    "hangul": "포황",
    "name": "蒲黃(포황)",
    "groupKey": "E",
    "groupTitle": "E그룹: 노란 절편·황색 분말류",
    "source": "12주차까지",
    "photoPage": 164,
    "namePage": 165,
    "tip": "선명한 노란 꽃가루 한 컵 -> 蒲黃.",
    "image": "assets/082.jpeg"
  },
  {
    "id": 83,
    "hanja": "茜草根",
    "hangul": "천초근",
    "name": "茜草根(천초근)",
    "groupKey": "D",
    "groupTitle": "D그룹: 갈색 뿌리·근경 절편류",
    "source": "12주차까지",
    "photoPage": 166,
    "namePage": 167,
    "tip": "붉은 실뿌리가 꼭두서니 색을 낸다 -> 茜草根.",
    "image": "assets/083.jpeg"
  },
  {
    "id": 84,
    "hanja": "艾葉",
    "hangul": "애엽",
    "name": "艾葉(애엽)",
    "groupKey": "F",
    "groupTitle": "F그룹: 잎·전초·줄기 조각류",
    "source": "12주차까지",
    "photoPage": 168,
    "namePage": 169,
    "tip": "회록색 잎 조각이 쑥 향을 바로 떠올린다 -> 艾葉.",
    "image": "assets/084.jpeg"
  },
  {
    "id": 85,
    "hanja": "川芎",
    "hangul": "천궁",
    "name": "川芎(천궁)",
    "groupKey": "D",
    "groupTitle": "D그룹: 갈색 뿌리·근경 절편류",
    "source": "12주차까지",
    "photoPage": 170,
    "namePage": 171,
    "tip": "흰 속과 갈색 껍질이 섞인 둥근 절편 -> 川芎.",
    "image": "assets/085.jpeg"
  },
  {
    "id": 86,
    "hanja": "乳香",
    "hangul": "유향",
    "name": "乳香(유향)",
    "groupKey": "K",
    "groupTitle": "K그룹: 수지·검은 덩어리류",
    "source": "12주차까지",
    "photoPage": 172,
    "namePage": 173,
    "tip": "반투명 노란 수지 알갱이가 젖 냄새처럼 번진다 -> 乳香.",
    "image": "assets/086.jpeg"
  },
  {
    "id": 87,
    "hanja": "沒藥",
    "hangul": "몰약",
    "name": "沒藥(몰약)",
    "groupKey": "K",
    "groupTitle": "K그룹: 수지·검은 덩어리류",
    "source": "12주차까지",
    "photoPage": 174,
    "namePage": 175,
    "tip": "더 어둡고 끈적한 수지 조각 -> 沒藥.",
    "image": "assets/087.jpeg"
  },
  {
    "id": 88,
    "hanja": "玄胡索",
    "hangul": "현호색",
    "name": "玄胡索(현호색)",
    "groupKey": "D",
    "groupTitle": "D그룹: 갈색 뿌리·근경 절편류",
    "source": "12주차까지",
    "photoPage": 176,
    "namePage": 177,
    "tip": "노란 속을 보인 작은 조각들이 현란하게 섞였다 -> 玄胡索.",
    "image": "assets/088.jpeg"
  },
  {
    "id": 89,
    "hanja": "鬱金",
    "hangul": "울금",
    "name": "鬱金(울금)",
    "groupKey": "E",
    "groupTitle": "E그룹: 노란 절편·황색 분말류",
    "source": "12주차까지",
    "photoPage": 178,
    "namePage": 179,
    "tip": "길쭉한 노란 절편이 울퉁불퉁 -> 鬱金.",
    "image": "assets/089.jpeg"
  },
  {
    "id": 90,
    "hanja": "薑黃",
    "hangul": "강황",
    "name": "薑黃(강황)",
    "groupKey": "E",
    "groupTitle": "E그룹: 노란 절편·황색 분말류",
    "source": "12주차까지",
    "photoPage": 180,
    "namePage": 181,
    "tip": "진한 황색 껍질 절편이 강한 강황색 -> 薑黃.",
    "image": "assets/090.jpeg"
  },
  {
    "id": 91,
    "hanja": "莪朮",
    "hangul": "아출",
    "name": "莪朮(아출)",
    "groupKey": "E",
    "groupTitle": "E그룹: 노란 절편·황색 분말류",
    "source": "12주차까지",
    "photoPage": 182,
    "namePage": 183,
    "tip": "두꺼운 노란 단면에 거친 껍질이 붙었다 -> 莪朮.",
    "image": "assets/091.jpeg"
  },
  {
    "id": 92,
    "hanja": "三稜",
    "hangul": "삼릉",
    "name": "三稜(삼릉)",
    "groupKey": "C",
    "groupTitle": "C그룹: 흰색·담색 절편과 원형 절편류",
    "source": "12주차까지",
    "photoPage": 184,
    "namePage": 185,
    "tip": "하얀 삼각 절편이 세 모서리를 강조한다 -> 三稜.",
    "image": "assets/092.jpeg"
  },
  {
    "id": 93,
    "hanja": "丹參",
    "hangul": "단삼",
    "name": "丹參(단삼)",
    "groupKey": "D",
    "groupTitle": "D그룹: 갈색 뿌리·근경 절편류",
    "source": "12주차까지",
    "photoPage": 186,
    "namePage": 187,
    "tip": "붉은 갈색 막대 절편이 단단하게 쌓였다 -> 丹參.",
    "image": "assets/093.jpeg"
  },
  {
    "id": 94,
    "hanja": "虎杖根",
    "hangul": "호장근",
    "name": "虎杖根(호장근)",
    "groupKey": "E",
    "groupTitle": "E그룹: 노란 절편·황색 분말류",
    "source": "12주차까지",
    "photoPage": 188,
    "namePage": 189,
    "tip": "커다란 노란 뿌리 조각이 호랑이 무늬처럼 거칠다 -> 虎杖根.",
    "image": "assets/094.jpeg"
  },
  {
    "id": 95,
    "hanja": "益母草",
    "hangul": "익모초",
    "name": "益母草(익모초)",
    "groupKey": "F",
    "groupTitle": "F그룹: 잎·전초·줄기 조각류",
    "source": "12주차까지",
    "photoPage": 190,
    "namePage": 191,
    "tip": "푸른 줄기와 잎이 익숙한 익모초 더미 -> 益母草.",
    "image": "assets/095.jpeg"
  },
  {
    "id": 96,
    "hanja": "桃仁",
    "hangul": "도인",
    "name": "桃仁(도인)",
    "groupKey": "B",
    "groupTitle": "B그룹: 작은 씨앗·곡물 알갱이류",
    "source": "12주차까지",
    "photoPage": 192,
    "namePage": 193,
    "tip": "납작한 복숭아씨 알맹이가 도톰하게 모였다 -> 桃仁.",
    "image": "assets/096.jpeg"
  },
  {
    "id": 97,
    "hanja": "紅花",
    "hangul": "홍화",
    "name": "紅花(홍화)",
    "groupKey": "I",
    "groupTitle": "I그룹: 꽃·꽃봉오리류",
    "source": "12주차까지",
    "photoPage": 194,
    "namePage": 195,
    "tip": "붉은 실꽃이 불꽃처럼 흩어졌다 -> 紅花.",
    "image": "assets/097.jpeg"
  },
  {
    "id": 98,
    "hanja": "五靈脂",
    "hangul": "오령지",
    "name": "五靈脂(오령지)",
    "groupKey": "M",
    "groupTitle": "M그룹: 벌레·동물성 검은 조각류",
    "source": "12주차까지",
    "photoPage": 196,
    "namePage": 197,
    "tip": "검은 작은 덩어리가 배설물처럼 빽빽하다 -> 五靈脂.",
    "image": "assets/098.jpeg"
  },
  {
    "id": 99,
    "hanja": "牛膝",
    "hangul": "우슬",
    "name": "牛膝(우슬)",
    "groupKey": "D",
    "groupTitle": "D그룹: 갈색 뿌리·근경 절편류",
    "source": "12주차까지",
    "photoPage": 198,
    "namePage": 199,
    "tip": "가느다란 흰 뿌리 조각 속에 소 무릎 같은 마디감 -> 牛膝.",
    "image": "assets/099.jpeg"
  },
  {
    "id": 100,
    "hanja": "蟅蟲",
    "hangul": "자충",
    "name": "蟅蟲(자충)",
    "groupKey": "M",
    "groupTitle": "M그룹: 벌레·동물성 검은 조각류",
    "source": "12주차까지",
    "photoPage": 200,
    "namePage": 201,
    "tip": "검은 벌레 몸통 조각이 그대로 보인다 -> 蟅蟲.",
    "image": "assets/100.jpeg"
  },
  {
    "id": 101,
    "hanja": "水蛭",
    "hangul": "수질",
    "name": "水蛭(수질)",
    "groupKey": "easy",
    "groupTitle": "바로 알아보기 쉬운 약재",
    "source": "12주차까지",
    "photoPage": 202,
    "namePage": 203,
    "tip": "검은 물거머리 조각이 휘어진다 -> 水蛭.",
    "image": "assets/101.jpeg"
  },
  {
    "id": 102,
    "hanja": "澤蘭",
    "hangul": "택란",
    "name": "澤蘭(택란)",
    "groupKey": "F",
    "groupTitle": "F그룹: 잎·전초·줄기 조각류",
    "source": "12주차까지",
    "photoPage": 204,
    "namePage": 205,
    "tip": "줄기와 잎이 섞인 연한 녹색 더미 -> 澤蘭.",
    "image": "assets/102.jpeg"
  },
  {
    "id": 103,
    "hanja": "凌霄花",
    "hangul": "능소화",
    "name": "凌霄花(능소화)",
    "groupKey": "I",
    "groupTitle": "I그룹: 꽃·꽃봉오리류",
    "source": "12주차까지",
    "photoPage": 206,
    "namePage": 207,
    "tip": "꽃잎 조각이 누렇게 능선처럼 벌어졌다 -> 凌霄花.",
    "image": "assets/103.jpeg"
  },
  {
    "id": 104,
    "hanja": "自然銅",
    "hangul": "자연동",
    "name": "自然銅(자연동)",
    "groupKey": "L",
    "groupTitle": "L그룹: 광물·분말·돌가루류",
    "source": "12주차까지",
    "photoPage": 208,
    "namePage": 209,
    "tip": "컵 속 검은 쇳가루 느낌 -> 自然銅.",
    "image": "assets/104.jpeg"
  },
  {
    "id": 105,
    "hanja": "王不留行",
    "hangul": "왕불류행",
    "name": "王不留行(왕불류행)",
    "groupKey": "F",
    "groupTitle": "F그룹: 잎·전초·줄기 조각류",
    "source": "12주차까지",
    "photoPage": 210,
    "namePage": 211,
    "tip": "초록 줄기 알갱이가 왕왕 잘려 있다 -> 王不留行.",
    "image": "assets/105.jpeg"
  },
  {
    "id": 106,
    "hanja": "蘇木",
    "hangul": "소목",
    "name": "蘇木(소목)",
    "groupKey": "H",
    "groupTitle": "H그룹: 목재 막대·긴 향신료류",
    "source": "12주차까지",
    "photoPage": 212,
    "namePage": 213,
    "tip": "붉은 목재 막대가 소나무가 아니라 소목색 -> 蘇木.",
    "image": "assets/106.jpeg"
  },
  {
    "id": 107,
    "hanja": "乾漆",
    "hangul": "건칠",
    "name": "乾漆(건칠)",
    "groupKey": "K",
    "groupTitle": "K그룹: 수지·검은 덩어리류",
    "source": "12주차까지",
    "photoPage": 214,
    "namePage": 215,
    "tip": "검은 옻 덩이가 말라 붙었다 -> 乾漆.",
    "image": "assets/107.jpeg"
  },
  {
    "id": 108,
    "hanja": "皂角刺",
    "hangul": "조각자",
    "name": "皂角刺(조각자)",
    "groupKey": "easy",
    "groupTitle": "바로 알아보기 쉬운 약재",
    "source": "12주차까지",
    "photoPage": 216,
    "namePage": 217,
    "tip": "뾰족한 보라색 가시가 조각조각 -> 皂角刺.",
    "image": "assets/108.jpeg"
  },
  {
    "id": 109,
    "hanja": "茺蔚子",
    "hangul": "충위자",
    "name": "茺蔚子(충위자)",
    "groupKey": "B",
    "groupTitle": "B그룹: 작은 씨앗·곡물 알갱이류",
    "source": "12주차까지",
    "photoPage": 218,
    "namePage": 219,
    "tip": "검은 깨보다 작은 씨가 빽빽하다 -> 茺蔚子.",
    "image": "assets/109.jpeg"
  },
  {
    "id": 110,
    "hanja": "卷柏",
    "hangul": "권백",
    "name": "卷柏(권백)",
    "groupKey": "easy",
    "groupTitle": "바로 알아보기 쉬운 약재",
    "source": "12주차까지",
    "photoPage": 220,
    "namePage": 221,
    "tip": "돌돌 말린 초록 식물 덩어리 -> 卷柏.",
    "image": "assets/110.jpeg"
  },
  {
    "id": 111,
    "hanja": "鷄血藤",
    "hangul": "계혈등",
    "name": "鷄血藤(계혈등)",
    "groupKey": "easy",
    "groupTitle": "바로 알아보기 쉬운 약재",
    "source": "12주차까지",
    "photoPage": 222,
    "namePage": 223,
    "tip": "닭피 같은 붉은 고리 무늬 절편 -> 鷄血藤.",
    "image": "assets/111.jpeg"
  },
  {
    "id": 112,
    "hanja": "半夏",
    "hangul": "반하",
    "name": "半夏(반하)",
    "groupKey": "C",
    "groupTitle": "C그룹: 흰색·담색 절편과 원형 절편류",
    "source": "12주차까지",
    "photoPage": 224,
    "namePage": 225,
    "tip": "작은 흰 알약 같은 덩이 -> 半夏.",
    "image": "assets/112.jpeg"
  },
  {
    "id": 113,
    "hanja": "天南星",
    "hangul": "천남성",
    "name": "天南星(천남성)",
    "groupKey": "C",
    "groupTitle": "C그룹: 흰색·담색 절편과 원형 절편류",
    "source": "12주차까지",
    "photoPage": 226,
    "namePage": 227,
    "tip": "반하보다 큰 흰 조각, 남쪽 별처럼 큼직하다 -> 天南星.",
    "image": "assets/113.jpeg"
  },
  {
    "id": 114,
    "hanja": "白附子",
    "hangul": "백부자",
    "name": "白附子(백부자)",
    "groupKey": "C",
    "groupTitle": "C그룹: 흰색·담색 절편과 원형 절편류",
    "source": "12주차까지",
    "photoPage": 228,
    "namePage": 229,
    "tip": "검은 껍질과 흰 속이 붙은 작은 조각 -> 白附子.",
    "image": "assets/114.jpeg"
  },
  {
    "id": 115,
    "hanja": "朱砂",
    "hangul": "주사",
    "name": "朱砂(주사)",
    "groupKey": "easy",
    "groupTitle": "바로 알아보기 쉬운 약재",
    "source": "13주차",
    "photoPage": 2,
    "namePage": 3,
    "tip": "붉은 모래 덩어리 -> 朱砂, 붉을 朱 + 모래 砂.",
    "image": "assets/115.jpeg"
  },
  {
    "id": 116,
    "hanja": "磁石",
    "hangul": "자석",
    "name": "磁石(자석)",
    "groupKey": "L",
    "groupTitle": "L그룹: 광물·분말·돌가루류",
    "source": "13주차",
    "photoPage": 4,
    "namePage": 5,
    "tip": "검은 돌 조각이 자석처럼 묵직하다 -> 磁石.",
    "image": "assets/116.jpeg"
  },
  {
    "id": 117,
    "hanja": "龍骨",
    "hangul": "용골",
    "name": "龍骨(용골)",
    "groupKey": "L",
    "groupTitle": "L그룹: 광물·분말·돌가루류",
    "source": "13주차",
    "photoPage": 6,
    "namePage": 7,
    "tip": "하얀 뼛가루가 그릇에 담겼다 -> 龍骨.",
    "image": "assets/117.jpeg"
  },
  {
    "id": 118,
    "hanja": "琥珀",
    "hangul": "호박",
    "name": "琥珀(호박)",
    "groupKey": "K",
    "groupTitle": "K그룹: 수지·검은 덩어리류",
    "source": "13주차",
    "photoPage": 8,
    "namePage": 9,
    "tip": "검정과 노랑이 섞인 수지 알갱이 -> 琥珀.",
    "image": "assets/118.jpeg"
  },
  {
    "id": 119,
    "hanja": "酸棗仁",
    "hangul": "산조인",
    "name": "酸棗仁(산조인)",
    "groupKey": "B",
    "groupTitle": "B그룹: 작은 씨앗·곡물 알갱이류",
    "source": "13주차",
    "photoPage": 10,
    "namePage": 11,
    "tip": "작고 붉은 갈색 씨앗이 산조 열매 씨처럼 둥글다 -> 酸棗仁.",
    "image": "assets/119.jpeg"
  },
  {
    "id": 120,
    "hanja": "柏子仁",
    "hangul": "백자인",
    "name": "柏子仁(백자인)",
    "groupKey": "B",
    "groupTitle": "B그룹: 작은 씨앗·곡물 알갱이류",
    "source": "13주차",
    "photoPage": 12,
    "namePage": 13,
    "tip": "연한 노란 씨가 촘촘한 잣가루처럼 보인다 -> 柏子仁.",
    "image": "assets/120.jpeg"
  },
  {
    "id": 121,
    "hanja": "遠志",
    "hangul": "원지",
    "name": "遠志(원지)",
    "groupKey": "D",
    "groupTitle": "D그룹: 갈색 뿌리·근경 절편류",
    "source": "13주차",
    "photoPage": 14,
    "namePage": 15,
    "tip": "연한 회갈색 뿌리가 멀리 뻗은 실처럼 보인다 -> 遠志.",
    "image": "assets/121.jpeg"
  },
  {
    "id": 122,
    "hanja": "合歡皮",
    "hangul": "합환피",
    "name": "合歡皮(합환피)",
    "groupKey": "G",
    "groupTitle": "G그룹: 껍질·판상 조각류",
    "source": "13주차",
    "photoPage": 16,
    "namePage": 17,
    "tip": "두 색 껍질이 휘어져 합쳐진 판 조각 -> 合歡皮.",
    "image": "assets/122.jpeg"
  },
  {
    "id": 123,
    "hanja": "靈芝",
    "hangul": "영지",
    "name": "靈芝(영지)",
    "groupKey": "G",
    "groupTitle": "G그룹: 껍질·판상 조각류",
    "source": "13주차",
    "photoPage": 18,
    "namePage": 19,
    "tip": "넓은 버섯 껍질 판이 영지의 광택을 남긴다 -> 靈芝.",
    "image": "assets/123.jpeg"
  },
  {
    "id": 124,
    "hanja": "夜交藤",
    "hangul": "야교등",
    "name": "夜交藤(야교등)",
    "groupKey": "H",
    "groupTitle": "H그룹: 목재 막대·긴 향신료류",
    "source": "13주차",
    "photoPage": 20,
    "namePage": 21,
    "tip": "밤색 줄기 토막이 밤길의 등나무처럼 많다 -> 夜交藤.",
    "image": "assets/124.jpeg"
  },
  {
    "id": 125,
    "hanja": "羚羊角",
    "hangul": "영양각",
    "name": "羚羊角(영양각)",
    "groupKey": "easy",
    "groupTitle": "바로 알아보기 쉬운 약재",
    "source": "13주차",
    "photoPage": 22,
    "namePage": 23,
    "tip": "포장 속 뿔 하나가 바로 눈에 박힌다 -> 羚羊角.",
    "image": "assets/125.jpeg"
  },
  {
    "id": 126,
    "hanja": "天麻",
    "hangul": "천마",
    "name": "天麻(천마)",
    "groupKey": "C",
    "groupTitle": "C그룹: 흰색·담색 절편과 원형 절편류",
    "source": "13주차",
    "photoPage": 24,
    "namePage": 25,
    "tip": "두꺼운 회갈색 덩이뿌리가 하늘에서 떨어진 마처럼 보인다 -> 天麻.",
    "image": "assets/126.jpeg"
  }
];
